export const avatarUrls = new Map([
  [
    'Blue',
    'https://drive.google.com/uc?export=view&id=1XnypQCnJVO9U5fo178Vo2LrEd_PgZkQ_',
  ],
  [
    'Cat',
    'https://drive.google.com/uc?export=view&id=1ePFfSxSD9w0ToWXFtocNtcRkM4mvX4-X',
  ],
  [
    'Cow',
    'https://drive.google.com/uc?export=view&id=1351Sn0NN6refchUXVrMx6AXL-oyR5lMT',
  ],
  [
    'Dog',
    'https://drive.google.com/uc?export=view&id=13Y43cB2J39VT-s8tN7oyJgPfaNDSHLc6',
  ],
  [
    'Giraffe',
    'https://drive.google.com/uc?export=view&id=16EBtYd4DhkEodC51da_Vj_KKboMLkAaA',
  ],
]);
